### ISSUE TITLE
Plugin fails when encountering 't

### ISSUE THREAD

**Issue by TimvdLippe** [aaschmid/gradle-cpd-plugin#13] opened 2015-08-26 12:27 UTC
Running `./gradlew cpd` results in a
> Execution failed for task ':cpdCheck'.
> Lexical error in file /home/tim/Projects/mockito/src/main/java/org/mockito/internal/matchers/apachecommons/commons-lang-license.txt at line 182, column 61.  Encountered: " " (32), after : "\'t"

Which is a license.txt with line 182:
> replaced with your own identifying information. (Don't include

where the plugin fails when it encounters the `'t` of the `Don't`

**Comment by aaschmid** [comment] 2015-08-26 16:44
Hi @JeremybellEU,
you can either exclude ```*.txt``` files or wait some days for the new version which will support ```skipLexicalErrors``` (see #12).

Exclusion could be achieved by e.g.
```
cpdCheck {
    exclude '*.txt'
}
```
as ```cpdCheck``` is a normal ```SourceTask``` (see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceTask.html)

**Comment by JeremybellEU** [comment] 2015-08-26 16:49
That would the given error for now, but will there be a fix for this problem in the future? Thanks in advance!

**Comment by aaschmid** [comment] 2015-08-26 16:56
Yes, the next version will implement the skipLexicalError option and I will release it soon.

**Comment by aaschmid** [comment] 2015-08-30 20:01
The new version [v0.5](https://github.com/aaschmid/gradle-cpd-plugin/releases/tag/v0.5) is released which introduces the above mentioned options. Please try it and give me feedback, otherwise we can think about another solution. Thanks

**Comment by JeremybellEU** [comment] 2015-09-02 16:30
Hello @aaschmid 

Sadly the issue is not resolved. My configuration:
```
buildscript {
  ...
  dependencies {
    ...
    classpath 'de.aaschmid.gradle.plugins:gradle-cpd-plugin:0.5'
  }
}

apply pluing: 'cpd'

cpd {
  language = 'java' // Line required to not cause any errors regarding cpd method not found
}

cpdCheck {
  skipLexicalErrors = false
}
```

Which still results in the above error.

**Comment by aaschmid** [comment] 2015-09-02 17:56
Hi @JeremybellEU, 
hm ... that is strange as my tests worked out perfectly (if the ```apply pluing``` in your snippet is just a typo). The language, though, is by default ```java``` ... and what do you mean with "Line required to not cause any errors regarding cpd method not found". Can you prepare a simple reproducer and upload it to github that I am able to reproduce your problem?

I got the following output by Gradle with just using the above settings:

```
:cpdCheck
Skipping ******/src/main/java/*******/license.txt. Reason: Lexical error in file ******src/main/java/*******/license.txt at line 1, column 55.  Encountered: " " (32), after : "\'t"
CPD found duplicate code. See the report at file:///*******/build/reports/cpd/cpdCheck.xml                                                      
```

**Comment by aaschmid** [comment] 2016-04-06 20:15
@TimvdLippe any news on that?

**Comment by TimvdLippe** [comment] 2016-04-06 20:46
Hey sorry for letting this unattended. The project in which I had to adopt this has already been completed and I did not continue to use this plugin. Therefore I can't fix the issue sadly.

**Comment by aaschmid** [comment] 2016-04-06 21:45
As I cannot reproduce and my test work fine, I will close this issue

**Closed by aaschmid** 2016-04-06 21:45 UTC
Labels: bug
