### ISSUE TITLE
Fix configuration cache issues

### ISSUE THREAD

**Issue by C-Otto** [aaschmid/gradle-cpd-plugin#54] opened 2020-11-26 18:02 UTC
The new incubating feature "configuration cache" seems to be incompatible with the plugin:

```
$ ./gradlew --configuration-cache help
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: help

[...]
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

2 problems were found storing the configuration cache, 1 of which seems unique.
- Plugin 'de.aaschmid.cpd': read system property 'file.encoding'
  See https://docs.gradle.org/6.8-rc-1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read

See the complete report at file:///home/cotto/IdeaProjects/playground/build/reports/configuration-cache/bry60ktvel38k530sjei30vdb/configuration-cache-report.html
> Read system property 'file.encoding'
> Read system property 'file.encoding'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
Configuration cache entry discarded with 2 problems.
```

https://docs.gradle.org/6.8-rc-1/userguide/configuration_cache.html

Stacktrace snippet:
```
org.gradle.api.InvalidUserCodeException: Read system property 'file.encoding'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:83)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
	at de.aaschmid.gradle.plugins.cpd.CpdExtension.<init>(CpdExtension.java:26)
	at de.aaschmid.gradle.plugins.cpd.CpdExtension_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by aaschmid** [comment] 2020-11-26 20:57
Thanks for this incompatibility report @C-Otto. I think the solution is making the `encoding` property a `Property`. Using `3.2-SNAPSHOT` on https://oss.sonatype.org/content/repositories/snapshots/ works for my other builds. You can use `id("de.aaschmid.cpd") version "3.2-SNAPSHOT"` by enhancing the `settings.xml` with 
```
pluginManagement {
    repositories {
        maven { 
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        gradlePluginPortal()
    }
}
```
Would be helpful if you could try it :-)

**Comment by C-Otto** [comment] 2020-11-26 21:06
Yeah, that works:

```
BUILD SUCCESSFUL in 548ms
```

Thanks!

**Comment by C-Otto** [comment] 2020-11-26 21:07
That works with the `help` command above, but fails with "clean build":

`> Task 'cpdCheck' requires 'minimumTokenCount' to be greater than zero.`

Feel free to give it a try in my playground: https://github.com/C-Otto/playground/

I had to edit `buildSrc/build.gradle` (adding the snapshots repository).

**Comment by aaschmid** [comment] 2020-11-26 21:40
Do you also have another change unknown to me as "work on my machine"(TM)...
(But I at least saw a deprecation warning which I will also fix)

BTW as I accidentally saw "architecture-tests": Do you know https://www.archunit.org/ (open sourcen and build by the company I work for. Also on https://www.thoughtworks.com/radar/tools/archunit ;-))

**Comment by C-Otto** [comment] 2020-11-27 08:36
I open issues as soon as I see the need :)

I know about ArchUnit, have used it in projects - it's a great tool! It's on my TODO list, I want to use it in the playground project.

**Comment by aaschmid** [comment] 2020-11-27 12:13
Is your `> Task 'cpdCheck' requires 'minimumTokenCount' to be greater than zero.` error resolved / explainable? I still cannot reproduce it...

**Comment by C-Otto** [comment] 2020-11-27 16:31
Yes, I still see that issue. Reproducible with `./gradlew --configuration-cache --no-build-cache clean build`.

**Comment by aaschmid** [comment] 2020-11-27 19:20
On `main` branch, I don't have the issue with neither of your commands above :-(

I have the following changes:
```
diff --git a/buildSrc/build.gradle b/buildSrc/build.gradle
index 440fa03..ee189ea 100644
--- a/buildSrc/build.gradle
+++ b/buildSrc/build.gradle
@@ -3,11 +3,15 @@ plugins {
 }
 
 repositories {
+    maven {
+        url "https://oss.sonatype.org/content/repositories/snapshots/"
+    }
     gradlePluginPortal()
 }
 
 dependencies {
-    implementation 'de.aaschmid:gradle-cpd-plugin:3.1'
+    implementation 'de.aaschmid:gradle-cpd-plugin:3.2-SNAPSHOT'
     implementation 'gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.6.0'
     implementation 'net.ltgt.gradle:gradle-errorprone-plugin:1.3.0'
     implementation 'net.ltgt.gradle:gradle-nullaway-plugin:1.0.2'
```

**Comment by C-Otto** [comment] 2020-11-28 14:23
I had to run the `./gradlew --configuration-cache --no-build-cache cpdCheck` twice to see the error. The diff is identical to yours.

**Comment by C-Otto** [comment] 2021-03-27 10:25
As reported on November 28, building the second time triggers a failure. Reproduced with Gradle 7.0 RC1, Java 16, CPD 3.2-SNAPSHOT.

**Comment by C-Otto** [comment] 2021-03-27 10:29
To reproduce:
` git clone https://github.com/C-Otto/playground && cd playground && git checkout gradle-cpd-plugin-54 && ./gradlew --configuration-cache --no-build-cache clean build && ./gradlew --configuration-cache --no-build-cache clean build`

```
Reusing configuration cache.
> Task :application:cpdCheck FAILED
> Task :subproject-two:cpdCheck FAILED
> Task :subproject-one:compileJava FAILED

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':application:cpdCheck' (type 'Cpd').
  - Type 'Cpd' property 'encoding' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'encoding'.
      2. Mark property 'encoding' as optional.
    
    Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#value_not_set for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
[...]
```

**Comment by aaschmid** [comment] 2021-03-27 10:30
Yes, I have the same issue ;-)
And currently I am thinking about why the properties value is not stored in the configuration cache ...

**Comment by aaschmid** [comment] 2021-03-27 11:03
Unfortunately, I don't see any easy fixes for this, rather I need to rewrite a good part of the properties / configuration stuff of the plugin :-(

**Comment by aaschmid** [comment] 2021-03-27 13:39
Another yet strange thing is that my test application works with bfe0311, however your project does now complain about a `minimumTokenCount` again. Most likely I need to change all the properties to `Property` :-(

**Comment by aaschmid** [comment] 2021-03-27 17:22
At least I found the problem with `minimumTokenCount`, see https://github.com/gradle/gradle/issues/16657

**Comment by aaschmid** [comment] 2021-03-27 17:34
Remaining problem is as far as I can see not resolvable by me while I am doing the same as Gradle internall does with the `pmd` or `checkstyle` plugin :-(
![grafik](https://user-images.githubusercontent.com/567653/112729129-ea770880-8f2a-11eb-906f-ea58e50d31b0.png)

**Comment by aaschmid** [comment] 2021-03-27 17:54
@C-Otto with the newest `3.2-SNAPSHOT` and `./gradlew --configuration-cache --no-build-cache --configuration-cache-problems=warn clean cpdCheck` it should work on the second run (at least it does on my machine once I ensured the `3.2-SNAPSHOT` is re-downloaded as described in https://stackoverflow.com/a/62085606.

However the warning from above is skipped and I still have no clue where it comes from :-(

**Comment by C-Otto** [comment] 2021-03-27 18:05
Thank you! For Google's sake, here's the warning as text:

```
cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.0-rc-1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

From that page:

> Gradle model types (e.g. Gradle, Settings, Project, SourceSet, Configuration etc…​) are usually used to carry some task input that should be explicitly and precisely declared instead.

> For example, if you reference a Project in order to get the project.version at execution time, you should instead directly declare the project version as an input to your task using a Property<String>. Another example would be to reference a SourceSet to later get the source files, the compilation classpath or the outputs of the source set. You should instead declare these as a FileCollection input and reference just that.

I don't know how that relates to the plugin, though.

**Comment by aaschmid** [comment] 2021-03-27 18:50
Unfortunately, I never directly relate to `Project`, however indirectly through the stack in the screenshot. 

As far as I could analyse it, I inherit from `org.gradle.api.reporting.internal.TaskReportContainer` which inherited from ´org.gradle.api.reporting.internal.DefaultReportContainer` which has a field `enabled` of type `NamedDomainObjectSet` which is instantiated via `DefaultNamedDomainObjectSet`.

**Comment by C-Otto** [comment] 2021-03-27 23:18
Maybe this helps? https://github.com/gradle/gradle/pull/14628/files#diff-239c622f1af32f1bee008aa813579ded9fffeb072f25557cf8eb27801268c770
(got it as a suggestion in the Gradle slack)

**Comment by aaschmid** [comment] 2021-03-28 07:34
Thank you @C-Otto. To be honest I was professionally blinkered in a way that `project` was contained in a lambda configuring `report.getOutputLocation()` in the `CpdPlugin` which I indeed copied from `Gradle`s `PmdPlugin` however not from the latest version (facepalm).

**Comment by aaschmid** [comment] 2021-03-28 08:57
Merged to master, preparing for next release...

**Closed by aaschmid** 2021-03-28 08:57 UTC
Labels: accepted, bug, enhancement, fixed

**Comment by aaschmid** [comment] 2021-03-28 09:46
FYI https://github.com/gradle/gradle/issues/13490
