### ISSUE TITLE
Declare system property usage (for Gradle 7 configuration cache)

### ISSUE THREAD

**Issue by C-Otto** [aaschmid/gradle-cpd-plugin#56] opened 2021-03-16 08:24 UTC
With Gradle 7 M3 and `--configuration-cache` I get an error that the CPD plugin reads a system property that is not declared.

```
org.gradle.api.InvalidUserCodeException: Read system property 'file.encoding'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:83)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
	at de.aaschmid.gradle.plugins.cpd.CpdExtension.<init>(CpdExtension.java:26)
	at de.aaschmid.gradle.plugins.cpd.CpdExtension_Decorated.<init>(Unknown Source)
```

Possible fix: https://docs.gradle.org/7.0-milestone-3/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read

**Comment by aaschmid** [comment] 2021-03-16 21:12
hm ... actually thought that this is already fixed. However it seems not to.
Thanks for reporting @C-Otto. I will try to fix it asap for staying compatible with the next version.

**Comment by aaschmid** [comment] 2021-03-27 09:17
Duplicate of #54 ;-)

**Comment by C-Otto** [comment] 2021-03-27 10:18
Oh sorry, I forgot about the other issue... is there anything I can do now?

**Comment by aaschmid** [comment] 2021-03-27 10:27
No, I thing I got the remaining problem about this and will fix it by default encoding to `UTF-8`

**Closed** 2021-03-27 10:39 UTC
Labels: bug
